apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 2
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
        - "-text=echo"
        ports:
        - containerPort: 5678
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx # <----------------------------- # CHANGE THIS IF NOT USING NGINX INGRESS CONTROLLER
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer" # <--- # CHANGE THIS TO MATCH YOUR ClusterIssuer
spec:
  tls:
  - hosts:
    - echo.ostrike.com # <-------------------------------------------- # CHANGE THIS TO YOUR DOMAIN
    secretName: letsencrypt-echo-deployment # <---------------------------------- # THIS MUST BE UNIQUE PER INGRESS!!!
  rules:
  - host: echo.ostrike.com # <---------------------------------------- # CHANGE THIS TO YOUR DOMAIN
    http:
      paths:
      - backend:
          serviceName: echo
          servicePort: 80
