apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-lb
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - name: pg
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
